services:
  mongodb:
    image: mongo:8.0.0-rc9-jammy
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  backend:
    container_name: backendc
    build:
      context: ./backend
    ports:
      - "3200:3200"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      - PORT=3200
      - MONGO_URI=mongodb://mongodb:27017/users_db
      - MONGO_URI_USER = mongodb://mongodb:27017/users_db
      - MONGO_URI_TRAVEL = mongodb://mongodb:27017/travels_db
      - MONGO_URI_CAR = mongodb://mongodb:27017/cars_db
  frontend:
    container_name: frontendc
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV = production
      - REACT_APP_API_URL=http://18.117.174.189:3200
    stdin_open: true
    tty: true
